### ISSUE TITLE
Build failing on bitrise

### ISSUE THREAD

**Issue by CraigSiemens** [datatheorem/TrustKit#258]
It looks like the Bitrise build is failing because it's trying to use the 11.4 simulator but only iOS 12.0-12.4 simulators are available on the currently selected stack.

https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xcode-10.3.x.log#L1077-L1080

It should be a fairly quick change to update the iOS step to use a 12.x simulator, but it can only be done by the owner.

Here's the smallest change to the bitrise.yml file that I think should fix it. It just removes the iOS step truing to use an 11.x simulator. Though you may want to look into using a newer simulator version as well.

```yaml
---
format_version: '4'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios
trigger_map:
- push_branch: "*"
  workflow: Tests
- pull_request_source_branch: "*"
  workflow: Tests
workflows:
  Tests:
    steps:
    - activate-ssh-key@4.0.3:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.14: {}
    - cache-pull@2.0.1: {}
    - script@1.1.5:
        title: Do anything with Script step
    - certificate-and-profile-installer@1.10.1: {}
    - xcode-test@2.4:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - simulator_os_version: '12.0'
        - scheme: TrustKit
        title: iOS 12.0
    - xcode-test@2.4:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - simulator_os_version: '12.0'
        - simulator_device: Apple TV 4K
        - simulator_platform: tvOS Simulator
        - scheme: TrustKit tvOS
        title: tvOS 12.0
    - xcode-test-mac@1.4:
        title: macOS
        inputs:
        - scheme: TrustKit OS X
    - deploy-to-bitrise-io@1.3.19: {}
    - cache-push@2.0.5: {}
    after_run: []
app:
  envs:
  - opts:
      is_expand: false
    BITRISE_PROJECT_PATH: TrustKit.xcodeproj
  - opts:
      is_expand: false
    BITRISE_SCHEME: TrustKit
  - opts:
      is_expand: false
    BITRISE_EXPORT_METHOD: development
\
```
